In [15]:
#NORMALIZATION PROBLEM

# Import the convention to access the NumPy library
import numpy as np

#create an array of m x n random values
x=np.random.random((5, 5))

#This function will calculate the normalized values
X_normalized = (x-x.mean()) / x.std()

#Save the normalized array
np.save('X_normalized.npy', X_normalized)


#The following functions will display the matrix, calculate the mean and standard deviation, and show the normalized values
print("The Matrix:\n\n", x)
print("\nThe Mean: ", x.mean())
print("The Standard Deviation:", x.std())
print("\n The Normalized Values: \n", X_normalized)

The Matrix:

 [[0.5174363  0.1653358  0.36814148 0.94966785 0.92823728]
 [0.38408867 0.76829615 0.1059471  0.85663796 0.6600175 ]
 [0.65171186 0.77172397 0.01713484 0.64964963 0.05665006]
 [0.04439677 0.09525551 0.48795751 0.58920908 0.69446446]
 [0.91842432 0.92675344 0.04156899 0.5312246  0.88587336]]

The Mean:  0.5226321796833989
The Standard Deviation: 0.3212146345997268

 The Normalized Values: 
 [[-0.01617572 -1.11232909 -0.48095786  1.32944027  1.26272297]
 [-0.43131132  0.76479696 -1.29721699  1.03982117  0.42770567]
 [ 0.40184869  0.77546836 -1.57370581  0.39542859 -1.4506877 ]
 [-1.48883442 -1.33050186 -0.10794859  0.20726609  0.53494536]
 [ 1.23217343  1.25810352 -1.49763782  0.02674977  1.13083634]]


In [13]:
#DIVISIBLE BY 3 PROBLEM

#Import the convention to access the NumPy library
import numpy as np

#This function creates ndarrays withing a specific range
A = np.arange(1, 101) **2

#Reshape into 10x10 arrays
A = A.reshape(10, 10)      

#This function will filter the elements that are divisible by 3
div_by_3 = A[A % 3 == 0]    

#Save the the result as div_by_3.npy
np.save('div_by_3.npy', div_by_3)

#Display the original array and the filtered result
print("The Original Array: \n\n", A)
print("\nThe values that are divisible by 3: \n\n", div_by_3)


The Original Array: 

 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]

The values that are divisible by 3: 

 [   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
